language: node_js
node_js:
  - 10.16.3
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
deploy:
  - provider: pages
    local-dir: docs
    skip_cleanup: true
    target-branch: gh-pages
    github_token: $GITHUB_TOKEN
    keep-history: true
    # fqdn: sorayama.me
    on:
      branch: master
  - provider: releases
    github_token: $GITHUB_TOKEN
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run doc
